indent_style = "Block"
brace_style = "PreferSameLine"
enum_discrim_align_threshold = 20
struct_field_align_threshold = 20
format_code_in_doc_comments = true
format_macro_matchers = true
format_strings = true
imports_layout = "HorizontalVertical"
match_block_trailing_comma = true
imports_granularity = "Crate"
overflow_delimited_expr = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
use_field_init_shorthand = true
use_try_shorthand = true

unstable_features = true
